name: .NET Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    name: .NET Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: '9.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish ./Bermondsey/Bermondsey.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp /p:DeleteExistingFiles=true

    - name: Zip published output for WebJob
      run: zip -r bermondsey-webjob.zip ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-webjob
        path: bermondsey-webjob.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    if: github.event_name == 'push'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_96D1A3DE731F44FB9741220E75F6DA93 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_10B114341A1B4DCE9404AA8E0E87BE4C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8AF71521EDB14EA89B53DD2208EAADB3 }}

      - name: Deploy WebJob to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bermondsey'
          slot-name: 'Production'
          package: 'bermondsey-webjob.zip'
          type: 'webjob'
          webjob-name: 'DisruptionWorker'
          webjob-type: 'continuous'
          